db: Add unique reverse names
Required when there are multiple relationships to the same table,
resolving these errors in the generated code
```
SystemCheckError: System check identified some issues:

ERRORS:
transport.DriverComments.about_user: (fields.E304) Reverse accessor for 'transport.DriverComments.about_user' clashes with reverse accessor for 'transport.DriverComments.posting_user'.
	HINT: Add or change a related_name argument to the definition for 'transport.DriverComments.about_user' or 'transport.DriverComments.posting_user'.
transport.DriverComments.posting_user: (fields.E304) Reverse accessor for 'transport.DriverComments.posting_user' clashes with reverse accessor for 'transport.DriverComments.about_user'.
	HINT: Add or change a related_name argument to the definition for 'transport.DriverComments.posting_user' or 'transport.DriverComments.about_user'.
transport.Reservations.assigned_driver: (fields.E304) Reverse accessor for 'transport.Reservations.assigned_driver' clashes with reverse accessor for 'transport.Reservations.deleted_by_driver'.
	HINT: Add or change a related_name argument to the definition for 'transport.Reservations.assigned_driver' or 'transport.Reservations.deleted_by_driver'.
transport.Reservations.deleted_by_driver: (fields.E304) Reverse accessor for 'transport.Reservations.deleted_by_driver' clashes with reverse accessor for 'transport.Reservations.assigned_driver'.
	HINT: Add or change a related_name argument to the definition for 'transport.Reservations.deleted_by_driver' or 'transport.Reservations.assigned_driver'.

System check identified 4 issues (0 silenced).
```